import os
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from tqdm import tqdm
import gc
import joblib

def train_random_forest(input_dir='unet_binary_outputs', subsample_ratio=0.1, window_size=3, image_subsample_ratio=0.1):
    """
    Train a RandomForestClassifier on a subsample of the training set UNet binary outputs.
    """
    # Load training data
    # Note: Using the new filenames generated by generate_unet_binary_outputs.py
    train_binary_path = os.path.join(input_dir, 'unet_preds_train.npy')
    train_labels_path = os.path.join(input_dir, 'unet_labels_train.npy')
    
    if not os.path.exists(train_binary_path) or not os.path.exists(train_labels_path):
        print(f'Missing training data files at {input_dir}. Aborting...')
        return
    
    # Load data using mmap to be safe with memory
    train_binary = np.load(train_binary_path, mmap_mode='r')
    train_labels = np.load(train_labels_path, mmap_mode='r')
    
    print(f'Loaded training binary outputs with shape: {train_binary.shape}')
    print(f'Loaded training labels with shape: {train_labels.shape}')
    
    # Subsample images before feature enrichment
    num_samples = train_binary.shape[0]
    subsample_image_count = int(num_samples * image_subsample_ratio)
    image_indices = np.random.choice(num_samples, size=subsample_image_count, replace=False)
    
    # Load subsampled data into memory
    sub_binary = np.array(train_binary[image_indices])
    sub_labels = np.array(train_labels[image_indices])
    
    print(f'Subsampled training images to: {sub_binary.shape} (using {image_subsample_ratio*100}% of images)')
    
    # Enrich features by considering a neighborhood around each pixel
    num_samples, height, width, num_features = sub_binary.shape
    half_window = window_size // 2
    enriched_features = []
    enriched_labels = []
    
    print(f'Enriching features with a {window_size}x{window_size} window...')
    for i in tqdm(range(num_samples), desc='Processing training samples'):
        for h in range(half_window, height - half_window):
            for w in range(half_window, width - half_window):
                window_features = sub_binary[i, h-half_window:h+half_window+1, w-half_window:w+half_window+1, :]
                enriched_features.append(window_features.flatten())
                enriched_labels.append(sub_labels[i, h, w])
    
    X_train_full = np.array(enriched_features)
    y_train_full = np.array(enriched_labels)
    
    print(f'Enriched training data shape: {X_train_full.shape}')
    
    del sub_binary, sub_labels, enriched_features, enriched_labels
    gc.collect()
    
    # Subsample the enriched training data
    total_pixels = X_train_full.shape[0]
    subsample_size = int(total_pixels * subsample_ratio)
    indices = np.random.choice(total_pixels, size=subsample_size, replace=False)
    X_train = X_train_full[indices]
    y_train = y_train_full[indices]
    
    print(f'Subsampled enriched training data to: {X_train.shape}')
    
    del X_train_full, y_train_full
    gc.collect()
    
    param_grid = {
        'n_estimators': [50],
        'max_depth': [None, 10],
        'min_samples_split': [2],
        'min_samples_leaf': [1],
        'criterion': ['gini']
    }
    
    clf = RandomForestClassifier(random_state=42, n_jobs=-1)
    
    print('Performing hyperparameter tuning...')
    grid_search = GridSearchCV(clf, param_grid, cv=5, scoring='accuracy', n_jobs=1)
    grid_search.fit(X_train, y_train)
    
    print(f'Best parameters: {grid_search.best_params_}')
    print(f'Best CV score: {grid_search.best_score_:.4f}')
    
    best_clf = grid_search.best_estimator_
    model_save_path = os.path.join(input_dir, 'best_random_forest_model_unet.joblib')
    joblib.dump(best_clf, model_save_path)
    print(f'Best model saved to: {model_save_path}')

if __name__ == '__main__':
    # Use 50% of images and 20% of pixels from those for training (consistent with previous run)
    train_random_forest(window_size=3, image_subsample_ratio=0.5, subsample_ratio=0.2)
